
FROM splatai/runai:base


RUN mamba install -y \
    -c fastai -c pytorch -c conda-forge -c bioconda \
    jupyterlab \
    scikit-learn \
    pandas \
    polars \
    scanpy python-igraph leidenalg \
    matplotlib plotly seaborn bokeh \
    streamlit \
    accelerate \
    biopython \
    click \
    black \
    jedi \
    joblib \
    numba \
    fastai